### ISSUE TITLE
Using Library wih CC1101

### ISSUE THREAD

**Issue by BReflex** [sebmillet/RF433any#19]
Hello Thank You for this library i used it to decrypt my garage remote 
I am trying to use it with cc1101 and ELECHOUSE_CC1101_SRC_DRV 
Do you think it s possible ?

**Comment by sebmillet** [comment]
Hello

My lib will never work with cc1101. This is 100% sure: RF433any is totally based on a device that simply says "signal is low" versus "signal is high" over a DATA PIN. Then RF433any measures the timings between high's and low's and when a structure is found, it'll try to identify encoding and timing characteristics.

cc1101 is managing modulation/demodulation itself so you have to know the signal characteristics when using it, in advance.

Note that there is more to it: at the time I was interested in cc1101, I saw that there are ways to let it work in "snif" mode and adapt to any signal. Also it could be used with a supplementary "debug" circuit to analyze everything in depth. All this was way too complex for me, I just abandonned it.

**Comment by BReflex** [comment]
Thank you so much for your response! 
I really appreciate the time you took to provide such detailed information.
I will stick to the cheap receivers
