### ISSUE TITLE
Strugging to get any decoding

### ISSUE THREAD

**Issue by kk7ds** [sebmillet/RF433any#6]
Hi,

Thanks for this library. I really want to get this working, but have been struggling (a lot).

I have two sensor types ([prologue](https://github.com/merbanan/rtl_433/blob/master/src/devices/prologue.c) and [acurite](https://github.com/merbanan/rtl_433/blob/master/src/devices/acurite.c#L19)) for testing, both of which are decoded by rtl433 very well from a great distance. I'd like to be able to decode them with an arduino. I have tried several samples of two receiver modules (and RXB6 and MX-RM-5V). I'm unable to get anything to really work.

With the MX-RM-5V (which seems to be the best), [here](https://gist.github.com/kk7ds/01f9d41100a6fa26c1826a04d8dfed00) is a long capture with both of them sitting right next to the receiver.

It seems like the ones with the empty data are the prologue sensor (based on seeing when the transmit light blinks) and the one with the long data string is the acurite. (I really want the prologue one more than anything, but if I could get the acurite working I would switch a project to use that).

Since the acurite one has actual data (it seems) I tried using rf433recv to decode it, without success. It also seems like it should be a 7-byte payload, even though it's clearly longer, so I'm not sure it's working. I tried code like this:

```
    rf.register_Receiver(
    	RFMOD_TRIBIT, // mod
	    65535, // initseq
	    0, // lo_prefix
	    0, // hi_prefix
    	0, // first_lo_ign
    	244, // lo_short
    	784, // lo_long
    	748, // hi_short (0 => take lo_short)
    	1180, // hi_long  (0 => take lo_long)
    	180, // lo_last
    	9068, // sep
    	196,  // nb_bits
      callback1,
      2000
    );
```

..But I never get my callback. I also tried ```RFMOD_TRIBIT_INVERTED``` and ```RFMOD_MANCHESTER``` since it was unspecified by rf433any, but none of them work.

I'm at a bit of a loss, but would *really* appreciate some help if you can point me in the right direction. Thanks!

**Comment by sebmillet** [comment]
Hello

could you send the result of sniffing data? you get it with the library rf433snif, available here:
https://github.com/sebmillet/rf433snif

Thanks,

Regards, Sébastien Millet

**Comment by sebmillet** [comment]
need snif feedback to handle question... now closing issue.
